name    = "RandomTest"
uuid    = "b75900cc-ad60-4ba3-b7dc-d2abb275d94a"
authors = ["Rafael Fourquet <fourquet.rafael@gmail.com>"]
version = "0.1.0"

[deps]
Random           = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomExtensions = "fb686558-2515-59ef-acaa-46db3789a887"

[extras]
Statistics       = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test             = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Statistics", "Test"]
